server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: mysql123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka


resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s


feign:
  circuitbreaker:
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0   # capture all requests

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans