server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:order_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:mysql123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


eureka:
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}


resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s


feign:
  circuitbreaker:
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0   # capture all requests

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    prometheus:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true
